version: '2'
services:
  # 网关
  online-exam-gateway:
    restart: always
    ports:
      - 8000:8000
    environment:
      # 环境变量配置
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8761
      - CONFIG_HOST=online-exam-config
      - CONFIG_PORT=8769
      - CONFIG_LABEL=test
      - AUTH_HOST=online-exam-auth
      - AUTH_PORT=8081
      - ZIPKIN_HOST=
      - ZIPKIN_PORT=
      - REDIS_HOST=online-exam-redis
      - REDIS_PORT=6379
      - MYSQL_HOST=online-exam-mysql
      - MYSQL_PORT=3306
      - RABBIT_MQ_HOST=online-exam-rabbit-mq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=admin
      - RABBIT_MQ_PASSWORD=admin
    # 启动顺序
#    entrypoint: sh /wait-for-it.sh online-exam-auth:3000 -t 600 --
#    command: java -Djava.security.egd=file:/dev/./urandom -jar online-exam-gateway.jar
    container_name: online-exam-gateway
    hostname: online-exam-gateway
    image: registry.cn-hangzhou.aliyuncs.com/online-exam/online-exam-gateway:0.1.0

  # 用户服务
  online-exam-user:
    restart: always
    ports:
      - 4000:4000
    environment:
      # 环境变量配置
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8761
      - CONFIG_HOST=online-exam-config
      - CONFIG_PORT=8769
      - CONFIG_LABEL=test
      - AUTH_HOST=online-exam-auth
      - AUTH_PORT=8081
      - ZIPKIN_HOST=
      - ZIPKIN_PORT=
      - REDIS_HOST=online-exam-redis
      - REDIS_PORT=6379
      - MYSQL_HOST=online-exam-mysql
      - MYSQL_PORT=3306
      - RABBIT_MQ_HOST=online-exam-rabbit-mq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=admin
      - RABBIT_MQ_PASSWORD=admin
      - FDFS_HOST=online-exam-fdfs-tracker
      - FDFS_PORT=22122
      - ATTACHMENT_HOST=http://b.yourdomain.cn:8088
      - ATTACHMENT_PORT=80
    container_name: online-exam-user
    hostname: online-exam-user
    image: registry.cn-hangzhou.aliyuncs.com/online-exam/online-exam-user:0.1.0

  # 考试服务
  online-exam-exam:
    restart: always
    ports:
      - 35010:35010
    environment:
      # 环境变量配置
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8761
      - CONFIG_HOST=online-exam-config
      - CONFIG_PORT=8769
      - CONFIG_LABEL=test
      - AUTH_HOST=online-exam-auth
      - AUTH_PORT=8081
      - ZIPKIN_HOST=
      - ZIPKIN_PORT=
      - REDIS_HOST=online-exam-redis
      - REDIS_PORT=6379
      - MYSQL_HOST=online-exam-mysql
      - MYSQL_PORT=3306
      - RABBIT_MQ_HOST=online-exam-rabbit-mq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=admin
      - RABBIT_MQ_PASSWORD=admin
    container_name: online-exam-exam
    hostname: online-exam-exam
    image: registry.cn-hangzhou.aliyuncs.com/online-exam/online-exam-exam:0.1.0