version: '2'
services:
  # online-exam-web
  online-exam-web:
    image: tangyi/online-exam-web:0.1.0
    volumes:
      # 挂载nginx的配置文件
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    container_name: online-exam-web
    ports:
      - 80:80
    restart: always

  # online-exam-ui
  online-exam-ui:
    image: tangyi/online-exam-ui:0.1.0
    volumes:
      # 挂载nginx的配置文件
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    container_name: online-exam-ui
    ports:
      - 81:80
    restart: always
volumes:
  data:
    driver: local