version: '2'
services:
  # 注册中心
  online-exam-eureka:
    restart: always
    ports:
      - 8765:8765
    environment:
      - SPRING_PROFILES_ACTIVE=test
    container_name: online-exam-eureka
    hostname: online-exam-eureka
    image: tangyi/online-exam-eureka:0.1.0

#  # 配置中心
  online-exam-config:
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - online-exam-eureka
    links:
      - online-exam-eureka:online-exam-eureka
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8765
    container_name: online-exam-config
    hostname: online-exam-config
    image: tangyi/online-exam-config:0.1.0

volumes:
  data:
    driver: local