version: '2'
services:
  # 监控服务
  online-exam-admin:
    restart: always
    ports:
      - 5001:5001
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8765
      - CONFIG_HOST=online-exam-config
      - CONFIG_PORT=8888
      - REDIS_HOST=online-exam-redis
      - REDIS_PORT=6379
      - RABBIT_MQ_HOST=online-exam-rabbit-mq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=admin
      - RABBIT_MQ_PASSWORD=admin
    container_name: online-exam-admin
    hostname: online-exam-admin
    image: tangyi/online-exam-admin:0.1.0

  # zipkin服务
  online-exam-zipkin:
    restart: always
    ports:
      - 9411:9411
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=online-exam-eureka
      - EUREKA_PORT=8765
      - CONFIG_HOST=online-exam-config
      - CONFIG_PORT=8888
      - REDIS_HOST=online-exam-redis
      - REDIS_PORT=6379
      - RABBIT_MQ_HOST=online-exam-rabbit-mq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=admin
      - RABBIT_MQ_PASSWORD=admin
    container_name: online-exam-zipkin
    hostname: online-exam-zipkin
    image: tangyi/online-exam-zipkin:0.1.0

volumes:
  data:
    driver: local