server:
  tomcat:
    max-threads: 10 # Maximum amount of worker threads.
  port: 5001
spring:
  application:
    name: online-exam-admin
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    registry-fetch-interval-seconds: 10
logging:
  level:
    com.github.tangyi: debug