server:
  port: 4000
  tomcat:
    max-threads: 10 # Maximum amount of worker threads.
    min-spare-threads: 5 # Minimum amount of worker threads
    uri-encoding: UTF-8
spring:
  application:
    name: online-exam-user
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: utf-8
      force: true
      enabled: true
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: online-exam-config
        enabled: true
      profile: ${spring.profiles.active}
      label: develop
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/platform_test001?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@localhost:8765/eureka
    registry-fetch-interval-seconds: 10
# fastDfs
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:
    width: 150
    height: 150
  pool:
    maxTotal: 30
    maxTotalPerKey: 30
    maxWaitMillis: 10000
  trackerList: 127.0.0.1:22122
logging:
  level:
    com.github.tangyi: debug