server:
  port: 4000
spring:
  application:
    name: online-exam-user
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: online-exam-config
        enabled: true
      profile: ${spring.profiles.active}
      label: ${spring.profiles.active}
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/online_exam?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 11
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@localhost:8765/eureka
    registry-fetch-interval-seconds: 10