server:
  port: 4000
  tomcat:
    max-threads: 10 # Maximum amount of worker threads.
    min-spare-threads: 5 # Minimum amount of worker threads
    uri-encoding: UTF-8
spring:
  application:
    name: online-exam-user
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: utf-8
      force: true
      enabled: true
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: online-exam-config
        enabled: true
      profile: ${spring.profiles.active}
      label: develop
  datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:192.168.0.144}:${MYSQL_PORT:3306}/platform_test001?useUnicode=true&characterEncoding=utf-8
        username: platform_test001
        password: 11
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8765}/eureka
    registry-fetch-interval-seconds: 10
# fastDfs
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:
    width: 150
    height: 150
  pool:
    maxTotal: 30
    maxTotalPerKey: 30
    maxWaitMillis: 10000
  trackerList: ${FDFS_HOST:192.168.0.95}:${FDFS_PORT:22122}

# 系统配置
sys:
  fdfsHttpHost: ${ATTACHMENT_HOST:http://192.168.0.95}:${ATTACHMENT_PORT:80}  # fastDfs的HTTP配置
  zuulUploadUrl: zuul/admin/attachment/upload
  defaultAvatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif?imageView2/1/w/80/h/80

logging:
  level:
    com.github.tangyi: debug
    org.apache.http: info
    com.netflix: info