server:
  port: 8081
  tomcat:
    max-threads: 10 # 最大线程数
spring:
  application:
    name: online-exam-auth
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    registry-fetch-interval-seconds: 10
logging:
  level:
   com.github.tangyi: debug
   org.apache.http: info
   com.netflix: info