server:
  port: 8890
spring:
  application:
    name: online-exam-auth
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: online-exam-config
        enabled: true
      profile: ${spring.profiles.active}
      label: ${spring.profiles.active}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@localhost:8765/eureka
    registry-fetch-interval-seconds: 10