server:
  port: 3000
  tomcat:
    max-threads: 10 # 最大线程数
spring:
  application:
    name: online-exam-auth
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: ${CONFIG_HOST:online-exam-config}
        enabled: true
      profile: ${spring.profiles.active}
      label: develop
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8765}/eureka
    registry-fetch-interval-seconds: 10
logging:
  level:
   com.github.tangyi: debug
   org.apache.http: info
   com.netflix: info