server:
  port: 35010
  session:
    cookie:
      name: APPSESSIONID
spring:
  application:
    name: online-exam-exam
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: online-exam-config
        enabled: true
      profile: ${spring.profiles.active}
      label: develop
  datasource:
        name: test
        url: jdbc:mysql://192.168.0.144:3306/platform_test002?useUnicode=true&characterEncoding=utf-8
        username: platform_test001
        password: 11
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@localhost:8765/eureka
    registry-fetch-interval-seconds: 10
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

security:
  oauth2:
    client:
      client-id: online-exam
      client-secret: online-exam
      user-authorization-uri: http://localhost:3000/oauth/authorize
      access-token-uri: http://localhost:3000/oauth/token
      scope: server
    resource:
      jwt:
        key-uri: http://localhost:3000/oauth/token_key
logging:
  level:
    com.github.tangyi: debug