server:
  port: 8888
spring:
  application:
    name: online-exam-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wells2333/online-exam-config.git
          default-label: master
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@localhost:8765/eureka
    registry-fetch-interval-seconds: 10