server:
  port: 8769
  tomcat:
    max-threads: 10 # 最大线程数
spring:
  application:
    name: online-exam-config
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI:https://gitee.com/wells2333/online-exam-config.git} # 配置文件的Git地址
          default-label: ${CONFIG_LABEl:develop}  # 配置文件的Git分支，默认develop分支
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: online-exam-config
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    registry-fetch-interval-seconds: 10