server:
  port: 8888
  tomcat:
    max-threads: 10 # 最大线程数
spring:
  application:
    name: online-exam-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wells2333/online-exam-config.git
          default-label: test
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: online-exam-config
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8765}/eureka
    registry-fetch-interval-seconds: 10