server:
  tomcat:
    max-threads: 10 # Maximum amount of worker threads.

spring:
  application:
    name: online-exam-zipkin
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: ${CONFIG_HOST:online-exam-config}
        enabled: true
      profile: ${spring.profiles.active}
      label: test
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:11@${EUREKA_HOST:localhost}:${EUREKA_PORT:8765}/eureka
    registry-fetch-interval-seconds: 10
# 认证服务器地址
security:
  auth:
    server: http://${AUTH_HOST:localhost}:${AUTH_PORT:3000}
logging:
  level:
    com.github.tangyi: debug